#!/bin/bash
#
#kolmnurk
#
#read
for((r=1; r<5; r++))
do
	# veerud - tärnid
	# tärnide arv algab ühest
	# igal real tärnide arv ei tohi ületada rea numbri 
	for((t=1; t<$(($r + 1)); t++))
	do
	echo -n "* "
	done
	echo # reavahetus
done
