#!/bin/bash
#
# ip järgi arvuti kontrollimine
#for ((nr=1; nr<=10; nr++))

echo -n "Sisesta vahemiku algus"

read algus

echo -n "Sisesta vahemiku lopp"

read lopp
for((nr=$algus; nr<=$lopp; nr++))
#for ip in 172.23.13.{20..50}
do
	ip=172.23.13.$nr
	# teostame antud ip pingi 
	ping -c 1 $ip > /dev/null # väljund on kustutatud
	# kontrollime ping käsu tulemust, kas läks läbi
	if [ $? -eq 0 ]; then
	  #kui $? on 0 - korras
	echo "$ip - ok"
	#muidu
	else
	echo "$ip  - not"	
fi # if lause lõpp
done
