#!/bin/bash
#
# keskkonna ja oma muutujate kasutamine
#
# kasutame keskkonna muutuja nimega $USER
# tervitame kasutaja
echo "Tere, $USER!"
# kuupäeva väärtuse loomine 
# defineerime vastava väärtusega muutja 
kuupaev=`date +'%d. %B'`
# väljastame kuupäeva koos seletusega 
echo "Täna on $kuupaev"
