#!/bin/bash
#
# keskkonna ja oma muutujate kasutamine
#
# kasutame keskkonna muutuja nimega $USER
# tervitame kasutaja
echo "Tere, $USER!"
# kuupäeva väärtuse loomine 
# defineerime vastava väärtusega muutja 
kuupaev=`date +'%d. %B'`
# väljastame kuupäeva koos seletusega 
echo "Täna on $kuupaev"
# kella väärtuse loomine
# defineerime vastava väärtusega muutuja 
kell=`date +'%H:%M'`
# väljastame kella koos seletusega 
echo "Kell on $kell"
# loome antud kuu kalendri
kalender=`cal`
#väljastame koos seletustega
echo "Antud kuu kalender :"
echo "-------------------------"
echo "$kalender"
echo "-------------------------"

