#!/bin/bash
#
# arvu kontroll - positiivne või negatiivne
#
# kontrollime, kas on sisestaud 1 parameeter
# vaatame, kui ei ole nii, siis trükime välja kasutusjuhendi
if [ $# -ne 1 ]; then
   echo "Kasutusjuhend: "
   echo "$0 arv"
   echo "Näiteks: $0 5"
# kui on kõik korras ja parameetrite arv on 1
else
   arv=$1
   # nüüd kontrollime, kas arv on positiivne 
   # sel juhul arv peab olema suurem kui 0
   if [ $arv -gt 0 ]; then
      # jah, arv on suurem kui 0 - positiivne
      echo "$arv on positiivne"
   # muidu kui arv on väiksem  kui 0 - negatiivne
   elif [ $arv -lt 0 ]; then
      echo "$arv on negatiivne"
   # kui esimene tingimus või teine tingimus ei sobi - neutraalne
   else
      echo "$arv on neutraalne"
   # if lause tuleb korralikult lõpetada
   fi
# väline if lause tuleb ka korralikult lõpetada
fi 
