#!/bin/bash
#
# arvu kontroll - positiivne või negatiivne
#
echo -n "Sisesta arv: "
read arv
# nüüd kontrollime, kas arv on positiivne
# sel juhul arv peab olema suurem kui 0
if [ $arv -gt 0 ]; then
   # jah, arv on suurem kui 0 - positiivne
   echo "$arv on positiivne"
# muidu kui arv on väiksem  kui 0 - negatiivne
elif [ $arv -lt 0 ]; then
   echo "$arv on negatiivne"
# kui esimene tingimus või teine tingimus ei sobi - neutraalne
else
   echo "$arv on neutraalne"
# if lause tuleb korralikult lõpetada
fi
